# Generated by Django 3.1.5 on 2021-01-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_meal_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
