# Generated by Django 3.1.5 on 2021-01-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_remove_meal_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='expiration',
        ),
    ]
