# Generated by Django 3.1.5 on 2021-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_meal_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Received', 'Received'), ('Consumed', 'Consumed')], default='On The Way', max_length=12),
        ),
    ]
