# Generated by Django 3.1.5 on 2021-01-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20210109_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planning.delivery'),
            preserve_default=False,
        ),
    ]
