# Generated by Django 3.1.5 on 2021-01-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_meal_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
