# Generated by Django 3.1.5 on 2021-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_meal_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Received', 'Received'), ('Consumed', 'Consumed'), ('Expired', 'Expired')], default='On The Way', max_length=12),
        ),
    ]
