# Generated by Django 3.1.5 on 2021-01-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20210109_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealStatusChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
            ],
        ),
    ]
