# Generated by Django 3.1.5 on 2021-01-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_mealstatuschoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='planning.mealstatuschoice'),
        ),
    ]
