# Generated by Django 3.1.5 on 2021-01-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_auto_20210109_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.mealstatuschoice'),
        ),
    ]
