# Generated by Django 3.1.5 on 2021-01-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_auto_20210109_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='arrived',
            new_name='arrival',
        ),
    ]
