# Generated by Django 3.1.5 on 2021-01-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_auto_20210109_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
